name: ie-bank-frontend
on:
  push:
    paths:
      - 'frontend/**'  # Trigger only when frontend folder changes
    branches:
      - main
  workflow_dispatch:

env:
  FRONTEND_WEBAPP_DEV: dkumlin-fe-dev

jobs:
  build:
    runs-on: ubuntu-latest
    environment: 'Development'
    steps:
      - uses: actions/checkout@v3
      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json
      - name: npm install, build, and test
        env:
          NODE_ENV: ${{ vars.NODE_ENV }}
          VUE_APP_ROOT_API: ${{ vars.VUE_APP_ROOT_API }}
        run: |
          cd frontend
          npm ci
          npm run build -- --mode ${{ vars.NODE_ENV }}
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app-dev
          path: frontend/dist/

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Development'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app-dev
          path: .
      - uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.FRONTEND_WEBAPP_DEV }}
          package: .
      - name: Configure App Settings
        uses: azure/appservice-settings@v1
        with:
          app-name: ${{ env.FRONTEND_WEBAPP_DEV }}
          app-settings-json: |
            [
              {
                "name": "NODE_ENV",
                "value": "${{ vars.NODE_ENV }}"
              },
              {
                "name": "VUE_APP_ROOT_API",
                "value": "${{ vars.VUE_APP_ROOT_API }}"
              }
            ]
