name: ie-bank-frontend

on:
  push:
    paths:
      - 'frontend/**'  # Trigger only when frontend folder changes
    branches:
      - main
  workflow_dispatch:

env:
  FRONTEND_WEBAPP_DEV: dkumlin-fe-dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          cache: 'npm'

      - name: npm install, build, and test
        run: |
          cd frontend  # Navigate to the frontend directory
          npm install
          npm run build -- --mode development --dest dist-dev  # Build Vue.js app for development

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app-dev
          path: frontend/dist-dev/  # Upload the build output from frontend

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Development'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app-dev
          path: frontend/  # Download artifact for frontend deployment

      - uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      
      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.FRONTEND_WEBAPP_DEV }}
          package: frontend/  # Deploy the frontend artifact
