name: ie-bank-empty-students-b-rg

on:
  push:
    paths:
      - 'infra/scripts/**'  # Trigger only with changes in the scripts folder under infra
      - '.github/workflows/ie-bank-empty-students-b-rg.yml'  # Trigger on changes to this workflow file
  schedule:
    - cron: '59 21 * * *'  # Trigger at 21:59 UTC every day (equivalent to 23:59 CEST)
  workflow_dispatch:  # Allows for manual triggering

env:
  RESOURCE_GROUP_DEV: BCSAI2024-DEVOPS-STUDENTS-B-DEV
  RESOURCE_GROUP_UAT: BCSAI2024-DEVOPS-STUDENTS-B-UAT
  RESOURCE_GROUP_PROD: BCSAI2024-DEVOPS-STUDENTS-B-PROD
  SUBSCRIPTION_ID_DEV: e0b9cada-61bc-4b5a-bd7a-52c606726b3b  # Ensure the correct subscription ID is set

jobs:
  remove-resource-groups:
    runs-on: ubuntu-latest

    steps:
      # Checkout code
      - uses: actions/checkout@v3  # Ensure the latest checkout action

      # Log into Azure
      - uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          enable-AzPSSession: true 

      # Empty resource group - Students Dev
      - name: Empty resource group - Dev
        uses: azure/powershell@v2
        with:
          inlineScript: |
            ./infra/scripts/empty-resource-group -ResourceGroupName "${{ env.RESOURCE_GROUP_DEV }}" -SubscriptionId "${{ env.SUBSCRIPTION_ID_DEV }}"
          azPSVersion: "latest"

      # Empty resource group - Students UAT
      - name: Empty resource group - UAT
        uses: azure/powershell@v2
        with:
          inlineScript: |
            ./infra/scripts/empty-resource-group -ResourceGroupName "${{ env.RESOURCE_GROUP_UAT }}" -SubscriptionId "${{ env.SUBSCRIPTION_ID_DEV }}"
          azPSVersion: "latest"

      # Empty resource group - Students Prod
      - name: Empty resource group - Prod
        uses: azure/powershell@v2
        with:
          inlineScript: |
            ./infra/scripts/empty-resource-group -ResourceGroupName "${{ env.RESOURCE_GROUP_PROD }}" -SubscriptionId "${{ env.SUBSCRIPTION_ID_DEV }}"
          azPSVersion: "latest"
